### ISSUE TITLE
Encourage more successful offspring

### ISSUE THREAD

**Issue by dustinlacewell** [alenaksu/neatjs#17]
How can I tune the configuration so that when there are successful individuals, a higher percentage of the next generation will behave similarly to the best performing ancestors?

It seems like no matter what I do, a good percentage of the offspring are always quite divergent from the most successful from the last generation.

**Comment by alenaksu** [comment]
I think you can tune the `survivalThreshold` option. 
On every epoch organisms of each species are sorted by their fitness and only the fittest will be selected for reproduction (`survivalThreshold * population size`).

So, a smaller threshold should let you get the best performing of each species

**Comment by alenaksu** [comment]
hey @dustinlacewell, did my answer help? If so I'd close the issue
